apiVersion: lifecycle.keptn.sh/v1alpha2
kind: KeptnTaskDefinition
metadata:
  name: postgres-check
spec:
  function:
    inline:
      code: |
        import { Client } from "https://deno.land/x/postgres@v0.17.0/mod.ts";
        let config;
        try {
          config="postgres://ffs:ffs@example-ffspostgres:5432/ffs";

          const client = new Client(config);
          await client.connect();
          await client.end();
        }
        catch (error){
            console.error("Could not connect to the database")
            Deno.exit(1)
        }