apiVersion: lifecycle.keptn.sh/v1alpha2
kind: KeptnTaskDefinition
metadata:
  name: redis-check
spec:
  function:
    inline:
      code: |
        import {
            connect as redisConnect
          } from 'https://deno.land/x/redis/mod.ts';
        try {
             const redisClient = await redisConnect({
                hostname: 'example-redis',
                port: 6379,
               });
             await redisClient.ping()
        }
        catch (error){
                   console.error("Could not connect to the Redis")
                   Deno.exit(1)
        }