apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      operator.opentelemetry.io/collector-headless-service: Exists
  endpoints:
    - port: prometheus
      interval: 10s