apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-servicemonitor
spec:
  selector:
    matchLabels:
      app: opentelemetry
  endpoints:
    - port: prometheus
      interval: 10s